### ISSUE TITLE
Submit to DT?

### ISSUE THREAD

**Issue by PaulGrimshaw** [xogeny/ts-redux#1]
Hi, thanks for this.  Can I suggest you submit to the main repo?

**Comment by xogeny** [comment]
You'll have to be more specific...submit what to what main repo?

**Comment by PaulGrimshaw** [comment]
I mean submit to definitely typed:

http://definitelytyped.org/

**Comment by xogeny** [comment]
Submit what though?  The typings in `index.d.ts`?  But the typings are already included in the package and they are referenced by the `typings` field in `package.json`.  Why would submitting the to DT be useful?

**Comment by PaulGrimshaw** [comment]
I haven't submitted before, so you'd need to check the contribution guidelines. 

Why would it be useful?

On any project you could simply type "typings install dt~updeep" and it would install the definition, which typically what most users to to find definition packages.

**Comment by PaulGrimshaw** [comment]
Sorry, i now realise i was confused!  I google searched and found this looking for updeep definitions, didn't realise this was part of a bigger module!

What i was suggesting was to submit your updeep typescript definition file, as there is currently no existing one.

**Comment by xogeny** [comment]
Ah.  I see.  Well I'm not so interested in submitting that.  But feel free to submit what I have.
